spring:
  application:
    name: api-f

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    
server:
  error:
    include-stacktrace: never

auth:
  jwt:
    secret: ${JWT_SECRET:40A0DDDC5B4574DEFAA3942DE9652C102A815A209CBDD8F5E334671D5686DE1B3AFFF000322EBA67D359349F0FD407DDE0C6A5754522347C0B1478CF4B38C722}
    expiration: 120